.github/FUNDING.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/labeler.yml
.github/stale.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Add the normal pull request template, labeler.yml, CODE_OF_CONDUCT, etc. files to setup the repo :raised_hands: 
~**EDIT**: Wait a sec on merging this! Still have 1 or 2 small thigns incoming :wink:~ Good to go!

feat: add repo organisation files

---

docs/configuration/providers/oauth.md

To avoid more frequent questions like this https://github.com/nextauthjs/next-auth/issues/2685

improve OAuth docs

---

docs/adapters/overview.md

adding link to MongoDB Adapter page

---

docs/providers/github.md

fix: typo in providers/github.md

---

docs/configuration/providers.md
docs/configuration/providers/oauth.md
docs/getting-started/upgrade-to-v4.md
docs/providers/auth0.md
docs/providers/cognito.md
docs/providers/fusionauth.md
docs/providers/identity-server4.md
docs/providers/okta.md
docs/providers/onelogin.md
docs/providers/osso.md

Update docs for providers, that previously used `domain` to `issuer`, as `domain` has been removed.
Haven't found any.
N/A

Providers: domain -> issuer

---

src/pages/index.js

Fix example syntax error

---

docs/providers/eveonline.md

- update eveonline examples for v4

Update eveonline examples for v4

---

docs/warnings.md

Add documentation about typeorm warning message
https://github.com/nextauthjs/adapters/pull/224

Add typeorm adapter warning

---

docusaurus.config.js

Just wanted to get this change into a draft PR at least. Not sure how you feel about the rewording / adding of emojis to draw some more attention to it. There was also spacing issues on small screens, this is just short enough to work with the docusaurus break points and look nice at all screen sizes.
New:
Old:

fix: update announcement bar wording

---

docs/getting-started/upgrade-to-v4.md

Added `theme` changes to the migration `upgrade-to-v4.md` page.

feat: add change in theme to migration page

---

docs/getting-started/upgrade-to-v4.md

fix: revert wrong commit

---

docs/providers/azure-ad.md

Update `azure-ad` documentation page, based upon Balazs and my experience fixing the provider.

fix: azure-ad provider docs

---

docs/configuration/providers.md
docs/configuration/providers/credentials.md
docs/providers/credentials.md

Update documentation to point out a new feature in the Credentials Provider.
None
None

docs(signin): Update Credentials documentation

---

docs/errors.md

Grammar issues for `errors.md`
TBD/None

Fix grammar issues for errors.md

---

docs/providers/azure-ad-b2c.md
docs/providers/github.md

Detail the required Account table fields when using Azure AD B2C provider.
https://github.com/nextauthjs/next-auth/issues/3067

Added required fields in Account table.

---

src/pages/index.js

Added `function` keyword in the code snippet for `_app.jsx` on the landing page
N/A

Update index.js to correct minor mistake in code snippet

---

docs/adapters/fauna.md

See https://github.com/nextauthjs/adapters/discussions/290#discussioncomment-1575283

fix: update FaunaAdapter signature in example code

---

docs/configuration/initialization.md
sidebars.js

Based on a few questions, this documentation could be the source of truth when explaining how to do custom actions that are too specific to be included in the library.
Some related discussions:
https://github.com/nextauthjs/next-auth/discussions/3133
https://github.com/nextauthjs/next-auth/discussions/3156
https://github.com/nextauthjs/next-auth/discussions/2703

add Initialization docs

---

docs/configuration/options.md

See https://github.com/nextauthjs/next-auth/pull/3142

mention state cookie

---

docs/configuration/options.md
docs/getting-started/upgrade-to-v4.md

See https://github.com/nextauthjs/next-auth/pull/3144

rename session strategy

---

docs/configuration/providers/oauth.md
docs/getting-started/upgrade-to-v4.md
package-lock.json
package.json

Explains the `authorization`, `token`, `userinfo` and `client` options in detail. This should help developers in understanding how to configure their providers, or how to create new ones.

Improve oauth config docs

---

docs/configuration/callbacks.md

See https://github.com/nextauthjs/next-auth/pull/3140

Allow relative redirect URLs by default

---

docs/adapters/models.md
docs/adapters/prisma.md
docs/adapters/typeorm.md

Add info about naming convention updates for those that need it.
See: https://github.com/nextauthjs/adapters/discussions/306

docs(models): naming convention info

---

docs/getting-started/upgrade-to-v4.md

Remove duplicate `Adapters` upgrade section

docs: fix duplicate section

---

docs/getting-started/upgrade-to-v4.md

docs(upgrade-to-v4) Remove extra space in da ta

---

docs/providers/pipedrive.md

Added docs for Pipedrive as a new provider, because the lib does not have yet.

feat(provider): add Pipedrive provider

---

docs/adapters/overview.md
docs/adapters/sequelize.md
sidebars.js

This follows on from https://github.com/nextauthjs/adapters/pull/237 and adds the required docs for the sequelize adapter.

feat: Add Sequelize adapter docs

---

docs/providers/email.md

Add missing `nodemailer` to code example.

Add missing `nodemailer` to code example.

---

docs/adapters/neo4j.md
docs/adapters/overview.md
sidebars.js

Add neo4j adapter page and links in sidebar and overview page
https://github.com/nextauthjs/adapters/pull/186

Add neo4j adapter page and links in sidebar and overview page

---

docs/adapters/mongodb.md

On pair with the changes at https://github.com/nextauthjs/adapters/pull/323

simplify MongoDB adapter initialization

---

package-lock.json
package.json
src/css/index.css
src/pages/index.js

update all in-range updates so npm stops whining (a bit) and so the package-lock.json doesn't constantly diff.

chore: deps update in-range

---

docs/adapters/dgraph.md
docs/adapters/overview.md
sidebars.js

This follows on from nextauthjs/adapters#206 and adds the required docs for the dgraph adapter.

feat: adding dgraph adapter to docs

---

docs/tutorials.md

Added a tutorial link that helps someone get started with NextAuth.js in a Next.js project that uses the Prisma adapter connected to a PlanetScale database. 
@balazsorban44 suggested I add it to the docs here.

add Prisma adapter + PlanetScale tutorial link

---

docs/adapters/mikro-orm.md
sidebars.js

contributes to https://github.com/nextauthjs/adapters/pull/325

docs(mikroorm): add default mikro-orm howto

---

docs/adapters/dynamodb.md

Update dynamodb adapter docs for v4

doc(dynamodb): update dynamodb adapter docs for v4

---

docs/getting-started/example.md

Fixes link that currently points to non-existing branch and gives 404.

fix: update example app repo url

---

docs/adapters/mikro-orm.md

... and remove a bit of repetitive boilerplate

docs(mikro-orm): fix defaultEntities not spreaded

---

docs/tutorials.md
versioned_docs/version-v3/tutorials.md

Magic Link Authentication in Next.js with NextAuth and Fauna
I added a new tutorial for passwordless authentication with NextAuth + Fauna DB, with live example + code source.
None.
None.

Add new tutorial

---

docusaurus.config.js
versioned_docs/version-v3/configuration/providers.md

Follow up for #157, as discussed there.
- fix build error because of missing line
- remove unreleased documentation link as it's not relevant

Follow-up: Fix build, remove unreleased docs footer link

---

docs/providers/fusionauth.md

Updated configuration steps for FusionAuth, see https://github.com/nextauthjs/next-auth/pull/3376
N/A

Updated fusionauth documentation

---

docs/configuration/callbacks.md

Update callbacks.md file to fit v4 API.
```diff
- session: {jwt: false}
+ session: {strategy: "database"}
```
N/A
N/A

Patch 1: Update documentation to match v4 api.

---

docs/providers/azure-ad.md

Fix small typo

---

docs/tutorials/refresh-token-rotation.md

Fixed referenced js title for client side example

---

docs/adapters/prisma.md

ensure consistency between the two Prisma schemas

---

docs/configuration/callbacks.md
docs/configuration/events.md
docs/configuration/initialization.md
docs/configuration/options.md
docs/configuration/pages.md
docs/configuration/providers/credentials.md
docs/configuration/providers/oauth.md
docs/getting-started/example.md
docs/getting-started/introduction.md
docs/getting-started/rest-api.md

Fix grammar issues and spelling mistakes
Multiple pages with incorrect spelling and grammar.

Fix: Grammar issues

---

docs/providers/credentials.md

https://github.com/nextauthjs/docs/issues/163#issuecomment-987522397
Removed incorrect code comments in the example

Updating docs according to issue #163

---

docs/getting-started/client.md

Implementation should be agnostic to the consumer's knowledge of React hooks. If the page requires of authentication, it should be directly implemented by the library. If the consumer wants to run side effects (whatever it is to fetch or create data), they should implement a useEffect on their own.

Update Auth component

---

docs/configuration/options.md

Fix typo in options.md

---

docs/providers/patreon.md

Added Patreon provider documentation
https://github.com/nextauthjs/next-auth/discussions/3519

doc for patreon provider

---

docs/providers/email.md

Added import declaration because as someone who comes into this page, finding the right import declaration might take time.
Doc improvement rather than an issue.

Improvement: Add EmailProvider import declaration per example

---

docs/adapters/overview.md
docs/adapters/upstash-redis.md

Added docs for new Upstash Redis database adapter.

Add Upstash Redis Adapter docs

---

docs/adapters/sequelize.md

Documentation changes
Ref: https://sequelize.org/master/manual/getting-started.html

Correct syntax for using sequelize

---

docs/providers/workos.md

Fixes import in work os docs
Fixes an import in the WorkOS example docs.

Fix WorkOS Docs Example

---

docs/providers/authentik.md

Added the documentation for the Authentik Provider
https://github.com/nextauthjs/next-auth/pull/3625

Added docs for authentik provider

---

sidebars.js

Added upstash-redis adapter to the sidebar

add upstash-redis to sidebar

---

docs/faq.md

not really sure what to put here

Small typo

---

docs/providers/authentik.md

The domain in the note was corrected

Fixed Typo in Authentik Provider

---

docs/adapters/dynamodb.md

This PR supplements https://github.com/nextauthjs/adapters/pull/380 and should only be merged after that PR is merged into `nextauthjs/adapters`.
Added additional documentation around DynamoDB custom table schemas.
None

docs: update dynamodb adapter docs

---

docs/providers/trakt.md

Added documentation for the trakt provider
https://github.com/nextauthjs/next-auth/pull/3771

added trakt provider page

---

docs/getting-started/typescript.md

- added: how to keep default interface props, when augmenting a default prop
- improved spelling

chore(docs): update `typescript` guide

---

README.md

Add a note to the header of the README about the code having been moved to the new primary monorepo.

chore: add deprecation warning to README.md
