docs/getting-started/client.md
docs/getting-started/upgrade-to-v4.md

Following the removal of `staleTime` from the **client module** on `next`, we had to remove references to it in the docs.
Given `staleTime` is already implicitly set when setting `refetchInterval`, do you think we need to reword the `refetchInterval` docs a bit to indicate that? ✍🏼

fix(client): remove `staleTime`

---

docs/tutorials.md
docusaurus.config.js

Moved that magic.link tutorial under one of the existing categories so it wasn't standing out on its own. Also added a 'dev.to' badge to the tutorials linking there. Thought it looked nice as we already have a youtube specific one too. 
Also this left-over `sidebarCollapsible` option was giving me issues when running locally. I guess its something thats been removed? I saw you removed another one of these options in the previous PR to fix the banner issue.

chore: update dev.to tutorial links

---

docs/getting-started/upgrade-to-v4.md

Added some warnings/notes to communicate the wrong `4.0.0` release in the migration docs.
https://github.com/nextauthjs/next-auth/issues/2675

add v4 beta install notes

---

docs/providers/azure-ad.md

As per https://github.com/nextauthjs/next-auth/pull/2411#issue-949171828 , the new 'authorization' option replaces the the 'scope' option.
This commit updates the docs to reflect this change.
N/A
N/A

Replace the 'scope' option in code snippet

---

docs/adapters/dynamodb.md
docs/adapters/fauna.md
docs/adapters/firebase.md
docs/adapters/mongodb.md
docs/adapters/pouchdb.md
docs/adapters/prisma.md
docs/adapters/typeorm.md
docs/getting-started/upgrade-to-v4.md
docusaurus.config.js
src/pages/index.js

There has been a lot of user confusion in the beta phase of our v4 release, so I decided to make this more prominent across the whole documentation. It seems that people don't really read the migration guide, so we have to spread the same information around, and link back to the migration guide more often.
this is not a full PR, I am happy for suggestions if we can do even more!
Similar PR #29

make `beta` status more prominent

---

docs/errors.md

Add error that can happen due to the peer dependency node version requirement.

Add possible error due to peer dependency node version

---

docs/errors.md
docs/providers/email.md

Added step 3. reminder for configuring a database adapter. We actually already mention that the email provider requires a database to be setup in the "TIP" callout before the setup steps, but another reminder can't hurt.
See: https://github.com/nextauthjs/next-auth-example/pull/40

fix: add email db requirement reminder

---

docs/getting-started/upgrade-to-v4.md

Pointed out in https://github.com/nextauthjs/next-auth/discussions/2839

fix naming of `emailVerified` in migration docs

---

docs/providers/email.md

v4 no longer includes nodemailer as a dependency so it's needed to install it manually.

Added note that installing nodemailer is needed

---

docs/configuration/initialization.md

the path for catch all file to catch /api/auth/* is '/page/api/auth/[...nextauth].js' not '/page/api/' (that will make it catch '/api/*' which is wrong).

fix(docs): add missing `/auth`

---

docs/configuration/options.md
docs/faq.md

Adds info regarding the cookie chunking PR (https://github.com/nextauthjs/next-auth/pull/3101). These were the two places that seemed like obvious candidates for more info, feel free to add on to it obviously :+1: 
Fixes #99

feat: add info about cookie chunking

---

docs/providers/google.md

authorizationUrl has been replaced by the authorization attribute in V4. I have updated the example to show how to pass these parameters that were previously passed in the authorizationUrl.
I have tested the code of change to the example and it works for me. I did not require passing in the URL component.
This is my first time contributing so I am happy to make any modifications that may be requested of me.
I do not currently have an issue for this.
Let me know if you would like me to take a picture of the markdown render after the change.

Update Google Provider Authorization Example to V4

---

docs/providers/osu.md

Adds the provider documentation for Osu! matching the PR https://github.com/nextauthjs/next-auth/pull/3234
Should be merged after https://github.com/nextauthjs/next-auth/pull/3234 is done.

feat(providers): Add documentation for Osu! provider

---

docs/getting-started/upgrade-to-v4.md
package-lock.json

Mention in the **v4 migration guide** that a collection on the MongoDB adapter was renamed ( from `camelCase` to `snake_case` ).
Fixes #110

docs(adapters): v4 mention collection renamed

---

docs/configuration/options.md
docs/faq.md
docs/getting-started/upgrade-to-v4.md
docs/tutorials/refresh-token-rotation.md

Added links to the new refresh token example repo page in a few places.

docs: add refresh token example repo links

---

docs/configuration/providers/oauth.md

In the `userinfo` option section of `docs/configuration/providers/oauth.md`,  the key should be `request` instead of `requst`

typo in `oath.md`

---

docs/configuration/options.md

- Fix typo session to strategy: jwt section
```js
session: {
strategy: "database",
maxAge: 30 * 24 * 60 * 60, // 30 days
updateAge: 24 * 60 * 60, // 24 hours
}
```
There is no `session` in the session's property.
I changed `session` to `strategy`.

[Fix] Typo in options.md

---

docs/providers/github.md

Tip updated to reflect new behavior from [nextauthjs/next-auth#3302](https://github.com/nextauthjs/next-auth/pull/3302)

docs(providers): update GitHub tip with new next-auth behavior

---

docs/adapters/dgraph.md
docs/adapters/dynamodb.md
docs/adapters/fauna.md
docs/adapters/firebase.md
docs/adapters/mongodb.md
docs/adapters/neo4j.md
docs/adapters/pouchdb.md
docs/adapters/prisma.md
docs/adapters/sequelize.md
docs/adapters/typeorm.md
docs/configuration/initialization.md
docs/configuration/providers/oauth.md
docs/getting-started/example.md
docs/getting-started/upgrade-to-v4.md
docs/providers/slack.md
docusaurus.config.js
src/pages/index.js

Removed the `beta` tags and infos from a few places in the docs, including links that pointed specifically to github beta branch files. These links were changed to `main`, therefore if the file doesnt exist yet, the vercel build may fail at the docusaurus dead link check for now.
Therefore, these links may have to be reverted to `beta` and follow-up with another PR to change them to `main`, or somehow force the build/deploy, if they are blocking on vercel.

feat: remove beta info from docs

---

docs/adapters/prisma.md

Cloud providers that don't support the creation of databases can't migrate an existing DB without specifying a shadow database. Users will see this error:
```
Error: P3014
Prisma Migrate could not create the shadow database. Please make sure the database user has permission to create databases. Read more about the shadow database (and workarounds) at https://pris.ly/d/migrate-shadow
Original error: 
db error: ERROR: permission denied to create database
0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:354
1: migration_core::api::DevDiagnostic
at migration-engine/core/src/api.rs:108
```
This caught me off guard when setting up Prisma as my adapter. Despite there [being a link to …

Update prisma.md to reference shadow databases within db datasource.

---

docs/providers/credentials.md
src/pages/index.js

The Credentials Provider page somehow got an additional code block with a nonsense example. That is cleaned up.
Also the code examples / snippets on the homepage were lacking syntax highlighting, that is also remedied here.

docs: cleanup credentials provider page + homepage example syntaxhighlighting

---

docs/providers/okta.md

The file being linked to was renamed from `.js` to `.ts`. This updates the link to https://github.com/nextauthjs/next-auth/blob/main/src/providers/okta.ts.

Fix Okta Provider options link

---

docs/providers/credentials.md

It seems at some point the file went from `.js` to `.ts`

Fix Credentials Provider options link

---

docs/adapters/prisma.md
docs/providers/42.md

Add a missing `created_at` field as its needed to create the account table, without it prisma throws the error bellow

fix: add missing `created_at` field

---

docs/errors.md

Fixes a typo on https://next-auth.js.org/errors#no_secret

chore(docs): fix typo

---

docs/configuration/options.md

This removes the database property from the options document.  Database is no longer available in v4. see discussion [here](https://github.com/nextauthjs/docs/issues/174#issuecomment-993963189)
Remove database option from v4 docs

remove database property from options document

---

docs/getting-started/upgrade-to-v4.md

This PR fixes a typo on the "Missing `secret`" section of the upgrade guide docs.
- Fixed `you're` for `your`
N/A
N/A

docs(upgrade-to-v4): Fix typo

---

.gitignore
.vscode/extensions.json
docs/faq.md

Following [this issue](https://github.com/nextauthjs/docs/issues/174#issuecomment-993963189) and [this PR](https://github.com/nextauthjs/docs/pull/175) I updated the relevant section on the FAQs to clarify how to opt-in or not for `jwt` in **v4**.
https://github.com/nextauthjs/docs/issues/174
I added code [spell check](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) as a **VSCode** recommendation, to help contributors and us as well using that editor catch typos when writing new docs.

fix(faq): clarify v4 `jwt` configuration

---

docs/adapters/prisma.md

Add note about the underlying database type for String in Prisma.
Related tweet: https://twitter.com/aidevv_in/status/1471147949136637952

Add note about the String type for MySQL in Prisma

---

docs/adapters/dynamodb.md

Updating the CloudFormation template in the NextAuth DynamoDB Adapter example with the missing `TimeToLiveSpecification` config.
The current [NextAuth DynamoDB Adapter](https://next-auth.js.org/adapters/dynamodb) docs are awesome and include CDK and CloudFormation examples that help provision the database. While the CDK example appears correct and complete, the CloudFormation example is missing the `TimeToLiveSpecification` configuration. This change updates the example to include this missing configuration.
- Documentation update that reflects adding the missing `TimeToLiveSpecification` with the `expires` attribute to the NextAuth DynamoDB Adapter page.
N/A. The corresponding AWS CDK example looks correct.
The CDK example, which correctly includes the `expires` attribute for configuring …

Adding missing TimeToLiveSpecification

---

docs/adapters/models.md

Change `jwt: true` to `strategy: "jwt"`.
The documentation on the db models page is referencing the previous session option (`jwt: true`) but [the current option](https://next-auth.js.org/configuration/options#session) is `strategy: "jwt"`. 👍
- See also in the [example repo](https://github.com/nextauthjs/next-auth-typescript-example/blob/df66e3f1796f054064ec8b2807f09c9889dda7e4/pages/api/auth/%5B...nextauth%5D.ts#L71)

fix(docs): update NextAuthOptions.session option

---

docs/configuration/providers/credentials.md

Changed line 13 where import of CredentialsProvider was sourced using ` next-auth/providers/credentials` rather than " next-auth/providers/credentials";
Caused error in code when the code snippet is copied and placed in code due to syntax error.

Typo on Code Example for credentials.md

---

docs/providers/azure-ad.md

According to the provider source, the default image size returned by Azure-AD is 48x48 and not 64x64.
https://github.com/nextauthjs/next-auth/blob/main/src/providers/azure-ad.ts
None
N/a

Update default image size for Azure-AD provider

---

docs/getting-started/upgrade-to-v4.md

The change description now matches the [Models](https://next-auth.js.org/adapters/models).

Fixed description of change to expires_at

---

docs/providers/apple.md

It was confusing to follow. This cleans it up a bunch.

Restructure Sign In with Apple dev server instructions
